name: groc_shopy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  http: ^1.4.0
  go_router: ^15.1.2
  get: ^4.7.2
  gap: ^3.0.1
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  camera: ^0.11.1
  pie_chart: ^5.4.0
  fl_chart: ^0.71.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  auto_size_text: ^3.0.0
  internet_connection_checker_plus: ^2.7.2
  get_it: ^8.0.3
  logger: ^2.5.0
  flutter_paypal: ^0.2.1
  file_picker: ^10.2.0
  
  

dev_dependencies:
  build_runner: ^2.4.10
  flutter_gen_runner: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  flutter_launcher_icons: ^0.14.3

flutter_gen:
  output: lib/core/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: true
  ios:
    remove_alpha_ios: true
  image_path: "assets/icons/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/